### ISSUE TITLE
5.5.2 version fails to load

### ISSUE THREAD

**Issue by schwicke** [cernops/kibana-relational-filter#5]
Kibana throughs this error for me:
```
Uncaught TypeError: __webpack_require__(...).register is not a function (https://localhost:5602/kibana/bundles/kibana.bundle.js?v=8467:155)
```
on 5.5.2 if I try to load this plugin.

**Comment by suyogdilipkale** [comment]
what are the steps to install on windows & linux server?

**Comment by psaiz** [comment]
There were some changes in the way the javascripts have to be imported from 5.4.0 to 5.5.2. 

Now, there are different tags for 5.4.0 and 5.5.2

The easiest way to install it:

```
# Go to the plugins directory
cd /usr/share/kibana/plugins
#Download the plugin
wget https://github.com/cernops/kibana-relational-filter/archive/ES_5.5.2_2.zip
#Uncompress it
unzip ES_5.5.2_2.zip 
```

@suyogdilipkale , let us know if there are any issues
